### ISSUE TITLE
How to create a color distribution library on my own dataset？

### ISSUE THREAD

**Issue by Shinya754** [VL-Group/Natural-Color-Fool#1]
Your work is amazing! I have a question after running your code, how do I create a color distribution library (i.e. `150_20_hist.npy` you provided) on my own dataset?  I would like to try your code on other datasets, but I don't know how to create a color distribution library. Hope to get your answer, thank you!

**Comment by ylhz** [comment]
Apologies for the delayed response; I've been busy with work.

We appreciate your interest in our work and thank you for following it.
Regarding your request for code to create color distribution library, unfortunately, our current library does not include that functionality. However, if you're interested in building one yourself, you can refer to this repository for guidance: https://github.com/mahmoudnafifi/Image_recoloring

Good luck!
